name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
        run:
          rustup target add wasm32-unknown-unknown
          cargo install ic-cdk-optimizer wasm-opt
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
